export const responsePlaceHolder = [
  {
    createdBy: "ADMIN",
    createdOn: "2023-05-04T09:03:04.326+00:00",
    updatedBy: null,
    updatedOn: null,
    id: 27,
    userId: "vivek112",
    userName: "vivek112",
    password: "$2a$10$2EiUP.iQKB8lcsQwC7jPDetrWMZDCC6XeeDUd/QFIAP4iZffVru.e",
    email: "vivek.kumar@velocis.co.in",
    mobile: "7990821267",
    product_type: null,
    org_id: null,
    locked_status: "Y",
    incorrect_attempt: 0,
    incorrect_max_attempt_limit: 30,
    fisrt_login_status: "N",
    status: "N",
    department: null,
    country: null,
    roles: [],
    branch: {
      branchId: "NOIDA11",
      branchName: null,
      gstin: null,
      branchAddress: null,
    },
  },
  {
    createdBy: "ADMIN",
    createdOn: "2023-05-04T09:23:02.449+00:00",
    updatedBy: null,
    updatedOn: null,
    id: 28,
    userId: "dfg",
    userName: "vivedfgk112",
    password: "$2a$10$ApdfUWb8a6SBRNWgoXrBROfnWSQyMFnujidvol.taWzSgh3LcGpT6",
    email: "vivek.kumar@velocis.co.in",
    mobile: "7990821267",
    product_type: null,
    org_id: null,
    locked_status: "N",
    incorrect_attempt: 0,
    incorrect_max_attempt_limit: 30,
    fisrt_login_status: "N",
    status: "N",
    department: null,
    country: null,
    roles: [
      {
        roleId: "SUPERADMIN",
        roleDesc: "Super Admin",
      },
    ],
    branch: {
      branchId: "NOIDA11",
      branchName: null,
      gstin: null,
      branchAddress: null,
    },
  },
  {
    createdBy: "ADMIN",
    createdOn: "2023-05-04T09:24:26.930+00:00",
    updatedBy: null,
    updatedOn: null,
    id: 29,
    userId: "dfdfgg",
    userName: "dfg",
    password: "$2a$10$kPiLp0hBWWT801E8MyX0cO9u2lnI/HzMvucqiazDIMuGmw9qatjya",
    email: "vivek.kumar@velocis.co.in",
    mobile: "7990821267",
    product_type: null,
    org_id: null,
    locked_status: "N",
    incorrect_attempt: 0,
    incorrect_max_attempt_limit: 30,
    fisrt_login_status: "N",
    status: "N",
    department: null,
    country: null,
    roles: [
      {
        roleId: "PARTS_SALES_ADMIN",
        roleDesc: "Parts Sales Admin",
      },
    ],
    branch: {
      branchId: "NOIDA11",
      branchName: null,
      gstin: null,
      branchAddress: null,
    },
  },
  {
    createdBy: "ADMIN",
    createdOn: "2023-05-04T08:57:28.300+00:00",
    updatedBy: "ADMIN",
    updatedOn: "2023-05-30T06:52:20.284+00:00",
    id: 25,
    userId: "vivek",
    userName: "vivek",
    password: "$2a$10$o7g1RW6zihL9RvEqiZ89p.QHHmA0eZ08bHynhPJksZ4wFxsZbAJMK",
    email: "vivek.kumar@velocis.co.in",
    mobile: "7990821267",
    product_type: null,
    org_id: null,
    locked_status: "N",
    incorrect_attempt: 0,
    incorrect_max_attempt_limit: 30,
    fisrt_login_status: "N",
    status: "N",
    department: null,
    country: null,
    roles: [
      {
        roleId: "SUPERADMIN",
        roleDesc: "Super Admin",
      },
    ],
    branch: {
      branchId: "NOIDA11",
      branchName: null,
      gstin: null,
      branchAddress: null,
    },
  },
];
